version: "3.8"

services:
  react:
    stdin_open: true
    tty: true
    container_name: graphic-blog-client
    build:
      context: .
      dockerfile: ./client/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src:ro

  my-database:
    image: mysql:8.0.31
    container_name: graphic-blog-db
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
      MYSQL_ROOT_HOST: "%"

  server:
    depends_on:
      - my-database
    stdin_open: true
    tty: true
    container_name: graphic-blog-server
    build:
      context: .
      dockerfile: ./server/Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - ./server/src:/app/src:ro

volumes:
  mysql-volume:
